---
# handlers file for ansible_role_libvirt_client_configure
- name: "== Reload in redhat == Reload sshd"
  ansible.builtin.systemd_service:
    name: sshd.service
    state: reloaded
  when: ansible_os_family == 'RedHat'
- name: "== Reload in debian == Reload ssh"
  ansible.builtin.systemd_service:
    name: ssh.service
    state: reloaded
  when: ansible_os_family == 'Debian'
- name: "== Reload in all == Restart systemd-journald service"
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
